### ISSUE TITLE
Set Up Background Image for Alien Defender Game

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/alien-defender-game#1]
We need to set up a background image for the Alien Defender game to enhance the visual experience. Currently, the game has a black background, which doesn't align with the alien theme we're aiming for.

**Comment by shubhansu-kr** [comment]
Hi, I would like to get more input: 

1. Do we have a theme decided for this ? 
2. Do we have the background image we want to see ? Any mock/figma ? 
3. I can see an issue with theme toggler request. How does this issue align with it ? Do we want to keep same background for both the theme ? 

Thanks

**Comment by DhanushNehru** [comment]
Hi @shubhansu-kr 

1. Theme is Space or Aliens
2. Feel free to use any static jpeg or jpg image. If possible use a space gif
3. Yes you can use same or even different if needed

**Comment by shubhansu-kr** [comment]
Thanks for assigning me this. 

Will start woking on this soon

**Comment by shubhansu-kr** [comment]
Added this BG image  : 

![image](https://github.com/user-attachments/assets/413e2955-3558-45ba-9340-f4b0c37e38e3)

**Comment by shubhansu-kr** [comment]
Request to close this issue. @DhanushNehru 

This issue was resolved here #20
