### ISSUE TITLE
Bug Fix : Asteroid overlapping with space ship

### ISSUE THREAD

**Issue by shubhansu-kr** [DhanushNehru/alien-defender-game#11]
Asteroid is set to hit the frame boundary even if it's returned by the space ship. This creates overlap in the UI which is not desirable. 

Fix : If the asteroid is rebounded from space ship, it should consider thickness of space ship in the return check. 

This will enhance the experience of the game giving it a more realistic touch.

**Comment by yesahem** [comment]
On it @DhanushNehru
