### ISSUE TITLE
allow user to decide the speed of ball

### ISSUE THREAD

**Issue by kanikaa-3018** [DhanushNehru/alien-defender-game#12]
please assign me this task for hacktoberfest24

**Comment by yesahem** [comment]
Let me do it now @DhanushNehru 
@kanikaa-3018

**Comment by DhanushNehru** [comment]
Hi @yesahem , @kanikaa-3018  is already working on it, Get approval from @kanikaa-3018 and then proceed with your PR

**Comment by yesahem** [comment]
@DhanushNehru I have messaged you on twitter kindly check, want to talk more about this project (my twitter profile: x.com/heyshishu)

**Comment by DhanushNehru** [comment]
Please reach out via discord @yesahem

**Comment by yesahem** [comment]
> Please reach out via discord @yesahem

Done ✅
