### ISSUE TITLE
Add a SECURITY.md file to the repository

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/alien-defender-game#2]
To enhance the security of the Alien Defender game repository, we should include a SECURITY.md file. This file will provide guidelines for reporting security vulnerabilities and outline our approach to security practices.

**Comment by Raushan-Shahi** [comment]
I would like to work on this issue, Please assign me this.

**Comment by Brijeshthummar02** [comment]
hey i need email where they can send a detailed report to our security team via email. this i'm adding in SECURITY.md file so can you help me.?

*updated : i'm adding git repo link no need of email.

**Comment by DhanushNehru** [comment]
Instead of email, feel free to mention the discord server, which can be found in the readme

**Comment by Brijeshthummar02** [comment]
can you go through the changes and tell changes that to be made.

**Comment by Brijeshthummar02** [comment]
Share feedback for current pull request, and if it's fine than please do me a favor merge it in oct 1-2 when hacktoberfest starts so that i can claim merge request.

**Comment by DhanushNehru** [comment]
@Raushan-Shahi if you are still working on this update here within the next 3 days or I will  assign the issue to @Brijeshthummar02

**Comment by Raushan-Shahi** [comment]
I am working on this. I will raise PR from October 1st.

**Comment by shubhansu-kr** [comment]
@Raushan-Shahi Update ?

**Comment by Raushan-Shahi** [comment]
@DhanushNehru, I can't see the update on my Hactoberfest profile for this pull and merge request.

**Comment by shubhansu-kr** [comment]
He closed it by mistake i guess. Not sure though
