### ISSUE TITLE
[Enhancement] Add start game button

### ISSUE THREAD

**Issue by shubhansu-kr** [DhanushNehru/alien-defender-game#21]
Current Experience : When user loads the page, the game is automatically started and user had to start playing. 

Expected Experience : User should see a button to start the game. 

Task : Add menu to start the game.

**Comment by shubhansu-kr** [comment]
We can extend this issue to add pause game functionality as well.

**Comment by yesahem** [comment]
Can I work on this @shubhansu-kr @DhanushNehru if I make PR by today 1:30am max?

Please add labels here also..

**Comment by shubhansu-kr** [comment]
> Can I work on this @shubhansu-kr @DhanushNehru if I make PR by today 1:30am max?
> 

Yeah please.

**Comment by yesahem** [comment]
> > Can I work on this @shubhansu-kr @DhanushNehru if I make PR by today 1:30am max?
> 
> Yeah please.

Please assign and also kindly add labels @shubhansu-kr @DhanushNehru

**Comment by shubhansu-kr** [comment]
> > > Can I work on this @shubhansu-kr @DhanushNehru if I make PR by today 1:30am max?
> > 
> > Yeah please.
> 
> Please assign and also kindly add labels @shubhansu-kr @DhanushNehru 
> 

You can start working, dhanush will assign you when he is online. I am not a contributor

**Comment by yesahem** [comment]
> > > > Can I work on this @shubhansu-kr @DhanushNehru if I make PR by today 1:30am max?
> > > 
> > > 
> > > Yeah please.
> > 
> > 
> > Please assign and also kindly add labels @shubhansu-kr @DhanushNehru
> 
> You can start working, dhanush will assign you when he is online. I am not a contributor

Thanks, Will update once the PR is Ready!

**Comment by yesahem** [comment]
> > > > > Can I work on this @shubhansu-kr @DhanushNehru if I make PR by today 1:30am max?
> > > > 
> > > > 
> > > > Yeah please.
> > > 
> > > 
> > > Please assign and also kindly add labels @shubhansu-kr @DhanushNehru
> > 
> > 
> > You can start working, dhanush will assign you when he is online. I am not a contributor
> 
> Thanks, Will update once the PR is Ready!

PR is ready

**Comment by shubhansu-kr** [comment]
Where ? Can you reference it please

**Comment by yesahem** [comment]
> Where ? Can you reference it please

I Haven't make a PR yet but pushed it to my codebase 
wating for @DhanushNehru to assign me and labels to this issue

**Comment by shubhansu-kr** [comment]
Issue resolved here #27
