### ISSUE TITLE
[Enhancement] Update Game End Canvas.

### ISSUE THREAD

**Issue by shubhansu-kr** [DhanushNehru/alien-defender-game#22]
We get a Earth wins / Alien wins screen when player wins/loses the game along with an option to continue playing. Currently the text highlighting this issue is very small and does not fit the UX requirement.

We need bigger font to highlight the status and add button to continue playing the game.

**Comment by sidhanshamil** [comment]
@DhanushNehru I would like to work on this, can you assign this issue #22 to me

**Comment by shubhansu-kr** [comment]
Issue Resolved here #25
