### ISSUE TITLE
Add a CODE_OF_CONDUCT.md file to the repository

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/alien-defender-game#3]
To foster a positive and inclusive environment for all contributors and users of the Alien Defender game, we should establish a CODE_OF_CONDUCT.md file. This document will outline expected behavior and guidelines for participation in our community.

**Comment by shubhansu-kr** [comment]
I would like to work on this issue, Please assign me this.

**Comment by Brijeshthummar02** [comment]
i'm working on this.

**Comment by shubhansu-kr** [comment]
@Brijeshthummar02 Please request assignee before working on the issue.

**Comment by shubhansu-kr** [comment]
Request to close this issue. @DhanushNehru
