### ISSUE TITLE
Add Support for Arrow Key Controls

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/alien-defender-game#4]
To enhance the player experience in the Alien Defender game, we should implement support for controlling the spaceship using the arrow keys. This will provide an additional input method for players who prefer keyboard controls over mouse movement.

**Comment by shubhansu-kr** [comment]
I believe this is a much needed feature, would love to pick up if it's available.

**Comment by shubhansu-kr** [comment]
Thanks for assigning me this. 

Status : Started working on the issue.

**Comment by yesahem** [comment]
@DhanushNehru What's the status of this issue 
Would love to contribute to it

**Comment by shubhansu-kr** [comment]
@yesahem , I will work on this issue on weekends. If you want to contribute, get it assigned from @DhanushNehru .

**Comment by yesahem** [comment]
Hey @DhanushNehru please have a look onto the PR I have raise 

Please let me know can I improve this more

**Comment by DhanushNehru** [comment]
Looks great @yesahem
